agent:
    town: Town04
camera:
    resolution:
        width: 512
        height: 256
dataset:
    folder_path: data/second_dataset
    town: Town04
    num_episodes: 130
    episode_length: 30.0
    ignore_traffic_lights: true
training:
    learning_rate: 0.001
    batch_size: 16
    epochs: 2
    num_train_episodes: 120
    num_test_episodes: 10
    save_path: model/second_model.pl
