agent:
    town: Town05
    model_path: models/wp_multi_map_0/model_epoch_2.pt
camera:
    resolution:
        width: 512
        height: 256
dataset:
    folder_path: data/wp_multi_map
    num_train_episodes: 480
    train_towns:
        - Town01
        - Town02
        - Town04
        - Town10HD
    num_val_episodes: 20
    val_towns:
        - Town01
        - Town02
        - Town04
        - Town10HD
    num_test_episodes: 10
    test_towns:
        - Town05
    episode_length: 60.0
    ignore_traffic_lights: true
training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 20
    save_path: models/wp_multi_map_0
    use_wandb: true
model:
    predict:
        type: waypoints
        num_waypoints: 3
        waypoint_sampling_interval: 4
        # type: direct_controls
        # steer_loss_weight: 1.0
        # throttle_loss_weight: 0.5
        # brake_loss_weight: 0.0
