agent:
    town: Town04
    model_path: models/overnight_05_12_2023/epoch_9.pl
camera:
    resolution:
        width: 512
        height: 256
dataset:
    folder_path: data/overnight_08_12_2023
    num_train_episodes: 400
    train_towns:
        - Town01
        - Town04
        - Town05
        - Town10HD
    num_test_episodes: 40
    test_towns:
        - Town02
        - Town05
    episode_length: 60.0
    ignore_traffic_lights: true
training:
    learning_rate: 0.0005
    batch_size: 64
    epochs: 100
    save_path: models/overnight_08_12_2023
