agent:
    town: Town04
    model_path: models/overnight_05_12_2023/epoch_9.pl
camera:
    resolution:
        width: 512
        height: 256
dataset:
    folder_path: data/recreation_of_run_22
    num_train_episodes: 200
    train_towns:
        - Town04
    num_test_episodes: 20
    test_towns:
        - Town04
    episode_length: 60.0
    ignore_traffic_lights: true
training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 100
    save_path: models/recreation_of_run_22
