agent:
    town: Town04
    model_path: models/overnight_05_12_2023/epoch_9.pl
camera:
    resolution:
        width: 512
        height: 256
dataset:
    folder_path: data/val_split
    num_train_episodes: 12
    train_towns:
        - Town04
    num_val_episodes: 4
    val_towns:
        - Town04
    num_test_episodes: 4
    test_towns:
        - Town05
    episode_length: 10.0
    ignore_traffic_lights: true
training:
    learning_rate: 0.001
    batch_size: 16
    epochs: 2
    save_path: models/val_split
