agent:
    town: Town04
camera:
    resolution:
        width: 640
        height: 480
dataset:
    folder_path: data/first_dataset
    town: Town04
    num_episodes: 130
    episode_length: 30.0
    ignore_traffic_lights: true
training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 10
    num_train_episodes: 120
    num_test_episodes: 10
    save_path: model/first_model.pl
