agent:
    town: Town04
    model_path: models/overnight_05_12_2023/epoch_9.pl
camera:
    resolution:
        width: 512
        height: 256
dataset:
    folder_path: data/overnight_05_12_2023
    town: Town04
    num_episodes: 220
    episode_length: 60.0
    ignore_traffic_lights: true
training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 50
    num_train_episodes: 200
    num_test_episodes: 20
    save_path: models/overnight_05_12_2023
